// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://junsytvpkhcaahcdhuxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1bnN5dHZwa2hjYWFoY2RodXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTg4MzQsImV4cCI6MjA1ODI5NDgzNH0.Jk99jN86L0W5luwUiSdIRxTELBpqk5Nyhu6bMLs0EMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);